version: "3.8"
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: liftup-frontend:latest
    ports:
      - "3001:80"          
    env_file:
      - .env               
    restart: unless-stopped

  hardhat:
    build:
      context: ./
      dockerfile: Dockerfile.hardhat
    image: liftup-hardhat:latest
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - SEPOLIA_RPC_URL=${SEPOLIA_RPC_URL}
      - PRIVATE_KEY=${PRIVATE_KEY}
    entrypoint: ["tail", "-f", "/dev/null"]  # keep container running for interactive use