apiVersion: apps/v1
kind: Deployment
metadata:
  name: hardhat-deployment
  labels:
    app: hardhat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hardhat
  template:
    metadata:
      labels:
        app: hardhat
    spec:
      containers:
        - name: hardhat
          image: astha013/liftup-hardhat:latest
          imagePullPolicy: Always  # Minikube local build
          ports:
            - containerPort: 8545
          env:
            - name: SEPOLIA_RPC_URL
              valueFrom:
                secretKeyRef:
                  name: liftup-secrets
                  key: SEPOLIA_RPC_URL
            - name: PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: liftup-secrets
                  key: PRIVATE_KEY
---

apiVersion: v1
kind: Service
metadata:
  name: hardhat-service
spec:
  type: NodePort
  selector:
    app: hardhat
  ports:
    - protocol: TCP
      port: 8545
      targetPort: 8545
      nodePort: 30545   
