apiVersion: v1
kind: Secret
metadata:
  name: liftup-secrets
type: Opaque
stringData:
  INFURA_API_KEY: "https://sepolia.infura.io/v3/d5ba727e7b2b4f9da42589061c03ccea"
  PRIVATE_KEY: "3c2ac4be7503a6ad761e9354a2a4bd85b6b288900f45595b16fe9cc881c459ba"
